import { formatAmountPlain, formatMoney } from "@/lib/money";
import type { ReceiptData } from "@/lib/printing";

const PAYMENT_LABEL: Record<string, string> = {
  cash: "Cash",
  upi: "UPI",
  card: "Card",
};

/**
 * The 58 mm receipt, following the layout in the spec.
 *
 * This same component is the on-screen preview and the printed page — the
 * `@media print` rules in globals.css strip the surrounding chrome and nothing
 * else. One template, so the preview cannot lie about what comes out.
 *
 * `qrSvg` is rendered server-side and passed in as markup. Generating it on
 * the client would risk printing a blank square if the print dialog opened
 * before the script ran.
 */
export function Receipt({
  data,
  qrSvg,
  qrImageUrl,
}: {
  data: ReceiptData;
  /** Inline SVG built from the UPI URI. */
  qrSvg?: string | null;
  /** The owner's uploaded bank QR, which takes precedence when present. */
  qrImageUrl?: string | null;
}) {
  const { cafe, bill, lines, upi } = data;
  const showQr = Boolean(qrImageUrl || qrSvg);

  return (
    <article className="receipt">
      <header style={{ textAlign: "center" }}>
        <div style={{ fontSize: "13pt", fontWeight: 700, letterSpacing: "0.05em" }}>
          {cafe.name.toUpperCase()}
        </div>
        {cafe.tagline ? <div>{cafe.tagline}</div> : null}
        {cafe.address ? <div>{cafe.address}</div> : null}
        {cafe.phone ? <div>{cafe.phone}</div> : null}
      </header>

      <hr className="receipt-rule" />

      <section>
        <KeyLine label="Bill No" value={bill.number} />
        <KeyLine label="Date" value={bill.date} />
        <KeyLine label="Time" value={bill.time} />
        <KeyLine label="Customer" value={bill.customerName} />
        {bill.customerMobile ? (
          <KeyLine label="Mobile" value={bill.customerMobile} />
        ) : null}
      </section>

      <hr className="receipt-rule" />

      <section>
        <div className="receipt-row" style={{ fontWeight: 700 }}>
          <span>Item</span>
          <span>Qty</span>
          <span>Rate</span>
          <span>Amt</span>
        </div>

        {lines.map((line, index) => (
          <div className="receipt-row" key={`${line.name}-${index}`}>
            {/* Long item names wrap under themselves rather than pushing the
                numeric columns off the paper. */}
            <span style={{ overflowWrap: "anywhere" }}>{line.name}</span>
            <span>{line.quantity}</span>
            <span>{formatAmountPlain(line.unitPrice)}</span>
            <span>{formatAmountPlain(line.lineTotal)}</span>
          </div>
        ))}
      </section>

      <hr className="receipt-rule" />

      <section>
        <KeyLine label="Subtotal" value={formatAmountPlain(bill.subtotal)} align />
        <KeyLine label="Discount" value={formatAmountPlain(bill.discount)} align />
        <div
          className="receipt-total"
          style={{ display: "flex", justifyContent: "space-between", marginTop: "1mm" }}
        >
          <span>TOTAL</span>
          <span style={{ fontVariantNumeric: "tabular-nums" }}>
            {formatMoney(bill.total)}
          </span>
        </div>
      </section>

      <hr className="receipt-rule" />

      <div>Payment: {PAYMENT_LABEL[bill.paymentMethod] ?? bill.paymentMethod}</div>

      {showQr ? (
        <section style={{ textAlign: "center", marginTop: "2.5mm" }}>
          {qrImageUrl ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={qrImageUrl}
              alt="Scan to pay by UPI"
              style={{ width: "32mm", height: "32mm", objectFit: "contain" }}
            />
          ) : (
            // Inline SVG: vector, so it stays crisp at whatever DPI the thermal
            // head runs, and needs no network fetch at print time.
            <div
              style={{ width: "32mm", height: "32mm", margin: "0 auto" }}
              // The markup is generated by the qrcode library from our own
              // configured UPI ID, never from user-entered HTML.
              dangerouslySetInnerHTML={{ __html: qrSvg! }}
            />
          )}
          <div style={{ marginTop: "1mm" }}>Scan to Pay</div>
          {upi.id ? <div>{upi.id}</div> : null}
        </section>
      ) : null}

      <section style={{ textAlign: "center", marginTop: "3mm" }}>
        {cafe.footer ? <div>{cafe.footer}</div> : null}
        {cafe.tagline ? <div>{cafe.tagline}</div> : null}
      </section>
    </article>
  );
}

function KeyLine({
  label,
  value,
  align = false,
}: {
  label: string;
  value: string;
  align?: boolean;
}) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", gap: "1ch" }}>
      <span>{label}</span>
      <span
        style={{
          fontVariantNumeric: align ? "tabular-nums" : undefined,
          textAlign: "right",
          overflowWrap: "anywhere",
        }}
      >
        {value}
      </span>
    </div>
  );
}
